description = "CNAB bundle authoring and management tool"
test = { cmd = "porter version", expected = "porter v{{version}}" }

[[backends]]
full = "github:getporter/porter"

[backends.options]
asset_pattern = "porter-{{ os(macos='darwin') }}-{{ arch(x64='amd64') }}{% if os() == 'windows' %}.exe{% endif %}"
bin = "porter"

[backends.options.platforms.windows-x64]
bin = "porter.exe"

[backends.options.platforms.windows-arm64]
bin = "porter.exe"
